language: c

env:
  global:
    # Set defaults to avoid repeating in most cases
    - MAIN_CMD="pytest tests -s"
    - SETUP_CMD=""
    - EXE_PREFIX="/tmp/miniconda3"
    - CONDA_DEPS="gcc pytest requests numpy astropy"

matrix:
  fast_finish: true

  include:
  - os: linux
    sudo: false
    python: 2.7
    compiler: gcc

  - os: linux
    sudo: false
    python: 3.5
    compiler: gcc
    env:
      - SETUP_CMD="--remote-data"

  - os: osx
    python: 2.7
    env:
      - CFLAGS="-m64"
      - LDFLAGS="-m64 -Wl,-rpath $EXE_PREFIX/lib"
      - SETUP_CMD="--remote-data"

  - os: osx
    python: 3.5
    env:
      - CFLAGS="-m64"
      - LDFLAGS="-m64 -Wl,-rpath $EXE_PREFIX/lib"

  - os: osx
    python: 2.7
    compiler: clang
    env:
      - CC="clang"
      - CFLAGS="-arch x86_64"
      - LDFLAGS="-arch x86_64"

  - os: osx
    python: 3.5
    compiler: clang
    env:
      - CC="clang"
      - CFLAGS="-arch x86_64"
      - LDFLAGS="-arch x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CONDA_INSTALLER=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CONDA_INSTALLER=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - wget $CONDA_INSTALLER
  - bash Miniconda3-latest-*.sh -b -p $EXE_PREFIX
  - export PATH=$EXE_PREFIX/bin:$PATH

install:
  - conda install --yes $CONDA_DEPS
  - ./waf configure --prefix=$EXE_PREFIX
  - ./waf build
  - ./waf install

script:
  - $MAIN_CMD $SETUP_CMD
